-- =============================================
-- Sequences (for Identity Columns)
-- =============================================

CREATE SEQUENCE IF NOT EXISTS DBO.DBO_AWBUILDVERSION_SYSTEMINFORMATIONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS DBO.DBO_DATABASELOG_DATABASELOGID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS DBO.DBO_ERRORLOG_ERRORLOGID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Humanresources.HUMANRESOURCES_DEPARTMENT_DEPARTMENTID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Humanresources.HUMANRESOURCES_JOBCANDIDATE_JOBCANDIDATEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Humanresources.HUMANRESOURCES_SHIFT_SHIFTID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_ADDRESS_ADDRESSID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_ADDRESSTYPE_ADDRESSTYPEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_BUSINESSENTITY_BUSINESSENTITYID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_CONTACTTYPE_CONTACTTYPEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_EMAILADDRESS_EMAILADDRESSID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_PHONENUMBERTYPE_PHONENUMBERTYPEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Person.PERSON_STATEPROVINCE_STATEPROVINCEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_BILLOFMATERIALS_BILLOFMATERIALSID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_ILLUSTRATION_ILLUSTRATIONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_LOCATION_LOCATIONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCT_PRODUCTID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTCATEGORY_PRODUCTCATEGORYID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTDESCRIPTION_PRODUCTDESCRIPTIONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTMODEL_PRODUCTMODELID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTPHOTO_PRODUCTPHOTOID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTREVIEW_PRODUCTREVIEWID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_PRODUCTSUBCATEGORY_PRODUCTSUBCATEGORYID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_SCRAPREASON_SCRAPREASONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_TRANSACTIONHISTORY_TRANSACTIONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Production.PRODUCTION_WORKORDER_WORKORDERID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Purchasing.PURCHASING_PURCHASEORDERDETAIL_PURCHASEORDERDETAILID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Purchasing.PURCHASING_PURCHASEORDERHEADER_PURCHASEORDERID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Purchasing.PURCHASING_SHIPMETHOD_SHIPMETHODID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_CREDITCARD_CREDITCARDID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_CURRENCYRATE_CURRENCYRATEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_CUSTOMER_CUSTOMERID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SALESORDERDETAIL_SALESORDERDETAILID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SALESORDERHEADER_SALESORDERID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SALESREASON_SALESREASONID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SALESTAXRATE_SALESTAXRATEID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SALESTERRITORY_TERRITORYID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SHOPPINGCARTITEM_SHOPPINGCARTITEMID_SEQ START = 1 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS Sales.SALES_SPECIALOFFER_SPECIALOFFERID_SEQ START = 1 INCREMENT = 1;